main: com.coolguy1842.factions.Factions
name: factions
version: 1.0.0
api-version: "1.20"
author: coolguy1842
description: Factions Plugin
commands:
permissions:
    factions.query:
        default: op
    factions.execute:
        default: op