main: coolguy1842.discordrelay.DiscordRelay
name: DiscordRelayPlugin
version: "1.0"
description: A plugin for relaying chat messages to discord
load: POSTWORLD
author: coolguy1842
api-version: "1.20"
commands:

permissions:
